# -*- coding: utf-8 -*-
"""Backup1 of Backup of Backup_Find Face.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wUrrGkerinCrTJyel8Sga4rbtWsb0tgE

#**TASK 1:**

##**Import**
"""


#import face_recognition
import cv2
import gdown
import os


from tqdm import tqdm, trange
from keras.models import load_model
from distance import findCosineDistance
from embedding_gender import get_embedding_gender_image
from face_extraction import face_extraction
from popular_face import most_popular_face
from take_object import take_object
import pandas as pd
from subprocess import call
# import insightface

"""##**Face extraction**"""

def main(ROOT_dir, model_dir):
  
  model = load_model(model_dir)
  BIG_image_dir = os.path.join(ROOT_dir, "images")
  list_user_id = os.listdir(BIG_image_dir)
  list_user_id.sort()
  done = False
  while not done:
    if len(list_user_id) >= 2:
      for user_id in list_user_id[:-1]:
      #####
        print(f"{user_id} FACE EXTRACTION RUNNING............")
        face_extraction(os.path.join(BIG_image_dir, user_id))
        BIG_full_face = os.path.join(ROOT_dir, "pipeline-deepface/full_face")
        #list_full_face = os.listdir(BIG_full_face)
        image_dir = os.path.join(BIG_full_face, user_id)
        print(f"{user_id} FIND MOST POPULAR FACE RUNNING............")
        list_person, len_lst, list_embedding_person = most_popular_face(image_dir, model)
        try:
          len_lst, list_person, list_embedding_person = zip(*sorted(zip(len_lst, list_person, list_embedding_person), reverse= True))
          take_object(ROOT_dir, image_dir, list_person[0], list_embedding_person[0])
        except:
          print(f"ERROR: Can't find valid face in user {user_id}")
        try:
          call('rm ' + image_dir+ ' -r', shell=True)
          # call('rm ' + BIG_image_dir + '/' + user_id+ ' -r', shell=True)
        except:
          print(f"ERROR: Can't delete {user_id} folder")
    list_user_id = os.listdir(BIG_image_dir)
    list_user_id.sort()
    if "zzzz" in list_user_id and len(list_user_id) == 1:
      done = True
      print("DONE!!!")
      call('rm ' + BIG_image_dir + '/' + "zzzz"+ ' -r', shell=True)

if __name__ == '__main__':
  
  ROOT_dir = os.getenv('DEEPFACE_DATA')
  # a file
  model_dir = os.path.join(ROOT_dir, "pipeline-deepface", "model.h5")
  if "model.h5" not in os.listdir(os.path.join(ROOT_dir, "pipeline-deepface")):
    url = "https://drive.google.com/uc?id=1-GztQP5wlqfjz1llOBZrLqV-DcWip24S"
    gdown.download(url, model_dir, quiet=False)
  main(ROOT_dir, model_dir)